### ISSUE TITLE
Strange error when using lasso code with leaflet-curve

### ISSUE THREAD

**Issue by eric-g-97477** [zakjan/leaflet-lasso#50]
I have a code pen demonstrating the issue at https://codepen.io/ericg_off/pen/JjLGWLw

I am using:

- https://unpkg.com/leaflet@1.8.0/dist/leaflet.js
- https://unpkg.com/leaflet-lasso@2.2.8/dist/leaflet-lasso.umd.min.js
- https://unpkg.com/@elfalem/leaflet-curve@0.9.1/dist/leaflet.curve.js

To reproduce:

1. Click on the lasso control in the upper right corner.
2. Draw a lasso around the markers

The following error will appear:

```
t-spatial.esm.js:522 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at t (t-spatial.esm.js:522:15)
    at calc.ts:6:20
    at Array.filter (<anonymous>)
    at U (calc.ts:58:35)
    at e.finish (lasso-handler.ts:189:34)
    at e.onDocumentMouseUp (lasso-handler.ts:151:14)
t @ t-spatial.esm.js:522
(anonymous) @ calc.ts:6
U @ calc.ts:58
e.finish @ lasso-handler.ts:189
e.onDocumentMouseUp @ lasso-handler.ts:151


iframeConsoleRunner-7549a40147ccd0ba0a6b5373d87e770e49bb4689f1c2dc30cccc7463f207f997.js:1 mouseup event was missed
```

I am not sure if the actual bug is in the lasso code or in the curve code.

**Comment by zakjan** [comment]
The issue is that Curve plugin extends from L.Path instead of L.Polyline, see: https://github.com/elfalem/Leaflet.curve/blob/ace73f5bf264aefb2bbcdcf6f74955317459ed7c/src/leaflet.curve.js#L9

Therefore it fails to pass the following check: https://github.com/zakjan/leaflet-lasso/blob/a059288e4623c89adf87565453278977c891a606/src/calc.ts#L62

I'll need some time to come up with the most appropriate workaround.

**Comment by eric-g-97477** [comment]
Thank you for the confirmation. If I can be of assistance in solving the problem (providing some testing, etc.), please let me know.

**Comment by eric-g-97477** [comment]
I had a couple of random thoughts on this ... perhaps they will be helpful to you.

If I understand correctly, what is going on is when you find something that is a polyline, you can call .getBounds() to determine whether the lassoed area intersects with the polyline object. Likewise, if it is not a polyline,  it is assumed to be a geojson object and you can get the bounds for it as well because there is a standard way for doing so.

The issue then is that with L.path based objects, there may not be a standard way to determine the bounds of the object. 

I wonder if one could grab the HTMLElement represented by the L.path object, determine the bounds of the element in pixel coordinates and then use methods like `containerPointToLatLng` to get the bounds.

One other option might be to define that a L.path object must have a .trace() method (like leaflet-curve does) so that you can get coordinates along each segment of the path and then compute the bounds based on that.

**Comment by eric-g-97477** [comment]
The author of leaflet-curve noted that there is a .getBounds() (undocumented). Perhaps that is sufficient for the lasso code?

**Comment by zakjan** [comment]
I updated the code to call `getBounds` for all layers where available. Released as 2.2.9, please try it out.

**Comment by eric-g-97477** [comment]
I tried it out with my CodePen above, but something still does not appear to be working. It is using 2.2.9.

The error I am getting is:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at t (t-spatial.esm.js:522:15)
    at calc.ts:6:20
    at Array.filter (<anonymous>)
    at U (calc.ts:58:35)
    at e.finish (lasso-handler.ts:190:34)
    at e.onDocumentMouseUp (lasso-handler.ts:152:14)
```

**Comment by zakjan** [comment]
Ok, I see. I tried to publish another fix (2.2.10), but it didn't helped, because there is another issue, L.Path / L.Curve is missing another required method `toGeoJSON()`.

**Comment by zakjan** [comment]
Given the mathematical nature of bezier curves, I think that `toGeoJSON` method can't be easily added. @eric-g-97477 I'm sorry, but the combination of the two plugins is not feasible at the moment.
